from prompts.templates import (
    INTENT_ROUTER_SYSTEM,
    PLANNER_SYSTEM,
    SEARCH_AGENT_SYSTEM,
    CODE_AGENT_SYSTEM,
    READ_AGENT_SYSTEM,
    MATH_AGENT_SYSTEM,
    REFLECTION_SYSTEM,
    SYNTHESIZER_SYSTEM,
)
